language: java
jdk:
- openjdk8
script: "./gradlew build"
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
deploy:
  provider: releases
  api_key:
    secure: Bc1DLi3Yr0NDzHxTM7asSNaRAcM2rsK8qQBdJESIyLcaqLS2oYx76LxBIUHRPu2zaIkHYnPQncuRnAhicWT7PmhIAScJeVqhWefihykGAQzr4rNTacF5FmBPaY+FtZxAqV1Y63n41ePLR3iTWTVq6IbmJJXueQiIn45Ahq1kMJifRhdO0LYX55Po26xoQXPMDkCmNBpK5Q+kkTeK1Yc+bJWX9IkZcUs8C+C7RvrxkpHiEd3HJ1hRzyUhjUBJDfByvBJaaGOSG1mGWkhLofs/0oePgDzv5ztC5bs7GZTEEjqG+TYCRpbUHdOv7c9XXXRZC+HfpYNETezLqDEHu5kUPdHMBEvKz4jix5E9hPp5i1scskdIy4vCQIyhZjjyAdBtd0um549xTL80btp/Aun8vgk0BrXetQdiaMDI+TOwKGEdGOwcppwuaFYNj/MAxmkTuhxIgMGm74m0qgsjiE652c/vpKiTitmpWEekGMq2ft9BOSYsOTvRVVxzIlxtPzR1RDqXdPDgME/DzgtPn/1O9TkJjhJ85U2OvqH2lMA4f6M5nlPh9CCmFYz/SlNQ4XpKUEHeDZgRZTxfI+Rk37o6vTDnzuuKmc2VPplXHY76e9gBOaZRnaeErO6r78B4Y3GD0GON0+mmTCiP5aY67kCxjhoM5tHh4E5U5hfv1GE3q9A=
  file: build/libs/rconfix-*.jar
  file_glob: true
  on:
    repo: fraenkelc/RCONNewlineFix
    tags: true
  skip_cleanup: 'true'
before_install:
- openssl aes-256-cbc -K $encrypted_12c8071d2874_key -iv $encrypted_12c8071d2874_iv
  -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar
