language: java
jdk:
- oraclejdk8

sudo: false
install: "./gradlew setupCIWorkspace -s"
script: "./gradlew build -s"

cache:
  directories:
  - "$HOME/.gradle/caches"
  - "$HOME/.gradle/wrapper"
before_cache:
- find $HOME/.gradle/ -name '*.lock' -print -exec rm -f {} \;

deploy:
  provider: releases
  api_key:
    secure: YaYuF/HNskSB6mqZ34u4Zq5+bdauQd0XCJcPCROH47G1KywWter/Zo36U8ea8228gDmyXw947A7tec/TRkGAm8QoysIs18cO2fh6FY6NO0mxWpJ3TdwCOos2COfjjbTAJxHXjQPeK/Sp1hx54EY+OgIBR8CcBNy7+sI03qwurTDHEkvd7OAfd7Q/FjUc4M82LXw66Xd5DNd2AiINHQJ13v/rC0B11Smzfd50rTZrtmk/B/dlE9layFSyNCKNcLN1UeEEtTxxzgs1qgMEpk/yoPCu7yeh8VUGn+AIftrMwMlYdnbTHdgdRdBOGLzM9TL6wSA/Lf0yC8YpDRi3mSqzjTdWPxn6RemKSAaf95/WnmDZu4qBAOHJLu7zBZjrvPbjkogOGzDPawe+tlimAs6t9u6meXGG6taREkEPB/DbDIXMGNlwd5V81Hve7GmhecFdS2bdtKNNXPKZ+2Ugaea6HQIPEbugGgLT6cx1Jx9GSmdhHvD9rFVgD2PbzkVM+Cb/M9QXpyIJsNmiFCSP77/aYCrLHfww1UchS6IbVhpZZ2z8T9kzxW9DPUqFlzxmb17q1B0vQSIhc5k85gTDo2y9FCsuq5VzlLETyCi/60GPUeXpGePPRXXMutqZoNptHdkctnZIWKexnqCwHwiqVHuc5tAt/atHdzs0xbSILSg0oaw=
  file: build/libs/rconfix-*.jar
  file_glob: true
  skip_cleanup: true
  on:
    repo: fraenkelc/RCONNewlineFix
    tags: true
